package ventanas;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import controladores.ControladorVentanaPrincipal;
import controladores.ControladorVentanaRegister;
import modelo.Empresa;
import ventanas.Ventana_AltaTecnicos;

/**
 *
 * @author ignac
 */
public class Ventana_Login extends javax.swing.JFrame implements IVista_Login,KeyListener{

    /**
     * Creates new form Ventana_Login
     */
    public Ventana_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDnioid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldContra = new javax.swing.JTextField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jButtonAlta = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(103, 15, 163));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresa tus datos para ingresar");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 420, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dni/Id:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, -1));
        getContentPane().add(jTextFieldDnioid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 30));
        getContentPane().add(jTextFieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 260, 30));

        jButtonEntrar.setBackground(new java.awt.Color(106, 106, 140));
        jButtonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setActionCommand("ENTRAR");
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, 50));

        jButtonRegister.setBackground(new java.awt.Color(106, 106, 140));
        jButtonRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Registrarse");
        jButtonRegister.setActionCommand("REGISTRARTE");
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 180, 50));

        jButtonAlta.setBackground(new java.awt.Color(106, 106, 140));
        jButtonAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAlta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAlta.setText("Alta tecnicos");
        jButtonAlta.setActionCommand("ALTA");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 130, 40));

        jLabelFondo.setBackground(new java.awt.Color(103, 15, 163));
        jLabelFondo.setForeground(new java.awt.Color(103, 15, 163));
        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ignac\\OneDrive\\Documentos\\NetBeansProjects\\TrabajoFinal\\src\\resources\\imagen.jpg")); // NOI18N
        jLabelFondo.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabelFondo.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabelFondo.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAltaActionPerformed

                                                    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextFieldContra;
    private javax.swing.JTextField jTextFieldDnioid;
    // End of variables declaration//GEN-END:variables
    
    private String tecnico;
    @Override
 	public void setActionListener(ActionListener controlador) {
    	this.jButtonEntrar.addActionListener(controlador);
    	this.jButtonRegister.addActionListener(controlador);
    	this.jButtonAlta.addActionListener(controlador);
 	}

 	@Override
 	public void setWindowListener(WindowListener controlador) {
 		// TODO Auto-generated method stub
 		
 	}

 	@Override
 	public void ejecutar() {
 		setTitle("Ventana Login");
         pack();
         setVisible(true);
         setLocationRelativeTo(null);	
         jButtonEntrar.setEnabled(false);
 	}

 	@Override
 	public void cerrarVentana() {
 		setVisible(false); //Oculto la ventana
 	    dispose(); //Cierro la ventana	
 	}



 	@Override
 	public void lanzarVentanaEmergente(String mensaje) {
 		JFrame jFrame = new JFrame();
         JOptionPane.showMessageDialog(jFrame, mensaje);		
 	}

	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void keyReleased(KeyEvent e) {
		if(jTextFieldContra.getText().isEmpty() || jTextFieldDnioid.getText().isEmpty())
			jButtonEntrar.setEnabled(false);
		else {
			jButtonEntrar.setEnabled(true);
		}
	}

	@Override
	public void keyTyped(KeyEvent e) {	
	}
	
	
	public void setKeyListener() {
	    this.jTextFieldContra.addKeyListener(this);
	    this.jTextFieldDnioid.addKeyListener(this);
	}

	@Override
	public int getDnioid() {
	
		return Integer.parseInt(jTextFieldDnioid.getText());
	}

	@Override
	public String getContrasena() {
		return jTextFieldContra.getText();
	}

	@Override
	public void nombreUsuarioInvalido() {
		jTextFieldContra.setText("");
		jTextFieldDnioid.setText("");
		jButtonEntrar.setEnabled(false);
	}

	@Override
	public void contrasenaInvalida() {
		jTextFieldContra.setText("");
		jButtonEntrar.setEnabled(false);
	}


	public void getTecnico(String tecnico) {
		this.tecnico=tecnico;
	}
	
	public String ejecutaTecnicos() {
		Ventana_AltaTecnicos ventana_AltaTecnicos=new Ventana_AltaTecnicos(this,true);
		ventana_AltaTecnicos.setVisible(true);
		return tecnico;
	}
}
