/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;


/**
 *
 * @author ignac
 */
public class Ventana_MetodoDePago extends javax.swing.JDialog {

    /**
     * Creates new form Ventana_MetodoDePago
     */
    public Ventana_MetodoDePago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Ventana MetodoDePago");	
        setLocation(550,280);
        iVista_Principal=(IVista_Principal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonEfectivo = new javax.swing.JButton();
        jButtonTarjeta = new javax.swing.JButton();
        jButtonCheque = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elije el metodo de pago de este mes:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 19, 290, 28));

        jButtonEfectivo.setText("Efectivo");
        jButtonEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfectivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, -1, -1));

        jButtonTarjeta.setText("Tarjeta");
        jButtonTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 102, -1, -1));

        jButtonCheque.setText("Cheque");
        jButtonCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChequeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 102, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ignac\\OneDrive\\Documentos\\NetBeansProjects\\TrabajoFinal\\src\\resources\\imagen.jpg")); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
        iVista_Principal.setBoton("Efectivo");
        dispose();
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    private void jButtonChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChequeActionPerformed
    	iVista_Principal.setBoton("Cheque");
    	dispose();
    }//GEN-LAST:event_jButtonChequeActionPerformed

    private void jButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarjetaActionPerformed
    	iVista_Principal.setBoton("Tarjeta");
    	dispose();
    }//GEN-LAST:event_jButtonTarjetaActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheque;
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JButton jButtonTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
    
    private IVista_Principal iVista_Principal;
}
