/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import java.util.Observer;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author ignac
 */
public class Ventana_VisitaTecnico extends javax.swing.JFrame implements IVista{

    /**
     * Creates new form Ventana_VisitaTecnico
     */
    public Ventana_VisitaTecnico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
    
    @Override
 	public void setActionListener(ActionListener controlador) {
 	
 	}

 	@Override
 	public void setWindowListener(WindowListener controlador) {
 		this.addWindowListener(controlador);
 		
 	}

 	@Override
 	public void ejecutar() {
 		setTitle("Ventana Principal");
        pack();
        setVisible(true);
        setLocationRelativeTo(null);
 	}

 	@Override
 	public void cerrarVentana() {
 		setVisible(false); //Oculto la ventana
 	    dispose(); //Cierro la ventana	
 	}

 

 	@Override
 	public void lanzarVentanaEmergente(String mensaje) {
 		JFrame jFrame = new JFrame();
         JOptionPane.showMessageDialog(jFrame, mensaje);		
 	}

	@Override
	public void setKeyListener() {
		// TODO Auto-generated method stub
		
	}
	
	public void escribe(String mensaje) {
		
		
			jTextArea.append(mensaje);
		
	}
}
