/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowListener;

import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import controladores.ControladorVentanaLogin;

/**
 *
 * @author ignac
 */
public class Ventana_Register extends javax.swing.JFrame implements IVista_Register{

    /**
     * Creates new form Ventana_Register
     */
    public Ventana_Register() {
        initComponents();
        grupo1.add(jRadioButtonFisico);
        grupo1.add(jRadioButtonJuridico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabelDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordFieldContra = new javax.swing.JPasswordField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jRadioButtonFisico = new javax.swing.JRadioButton();
        jRadioButtonJuridico = new javax.swing.JRadioButton();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarse.setBackground(new java.awt.Color(106, 106, 140));
        jButtonRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.setActionCommand("REGISTRARSE");
        jPanel1.add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 200, 50));

        jLabelDni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDni.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDni.setText("Dni:");
        jPanel1.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));
        jPanel1.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 180, -1));
        jPanel1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 180, -1));
        jPanel1.add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 20, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 20, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 20, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Campos obligatorios");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 130, -1));
        jPanel1.add(jPasswordFieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 180, -1));
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 180, -1));
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, -1));

        jLabelApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellidos:");
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 100, -1));

        jButtonInicio.setBackground(new java.awt.Color(102, 102, 255));
        jButtonInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setText("Volver al inicio");
        jButtonInicio.setActionCommand("INICIO");
        jPanel1.add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jRadioButtonFisico.setText("Abonado Fisico");
        jRadioButtonFisico.setActionCommand("FISICO");
        jRadioButtonFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFisicoActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jRadioButtonJuridico.setText("Abonado Juridico");
        jRadioButtonJuridico.setActionCommand("JURIDICO");
        jPanel1.add(jRadioButtonJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabelId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("ID:");
        jPanel1.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 30, -1));
        jPanel1.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ignac\\OneDrive\\Documentos\\NetBeansProjects\\TrabajoFinal\\src\\resources\\imagen.jpg")); // NOI18N
        jLabelFondo.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFisicoActionPerformed

                                                    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContra;
    private javax.swing.JRadioButton jRadioButtonFisico;
    private javax.swing.JRadioButton jRadioButtonJuridico;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
    
   private ButtonGroup grupo1=new ButtonGroup(); 
    
    @Override
 	public void setActionListener(ActionListener controlador) {
    	this.jButtonInicio.addActionListener(controlador);
    	this.jButtonRegistrarse.addActionListener(controlador);
    	
    	this.jRadioButtonFisico.addActionListener(controlador);
    	this.jRadioButtonJuridico.addActionListener(controlador);
 	}

 	@Override
 	public void setWindowListener(WindowListener controlador) {
 		// TODO Auto-generated method stub
 		
 	}

 	@Override
 	public void ejecutar() {
 		setTitle("Ventana Register");
         pack();
         setVisible(true);
         setLocationRelativeTo(null);	
         jButtonRegistrarse.setEnabled(false);
         jRadioButtonFisico.setSelected(true);
         muestraFisico();
         
 	}

 	@Override
 	public void cerrarVentana() {
 		setVisible(false); //Oculto la ventana
 	    dispose(); //Cierro la ventana	
 	}



 	@Override
 	public void lanzarVentanaEmergente(String mensaje) {
 		JFrame jFrame = new JFrame();
         JOptionPane.showMessageDialog(jFrame, mensaje);		
 	}

	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void keyReleased(KeyEvent e) {
		if(jRadioButtonFisico.isSelected()) {
			if(jPasswordFieldContra.getText().isEmpty() || jTextFieldDni.getText().isEmpty())
				jButtonRegistrarse.setEnabled(false);
			else {
				jButtonRegistrarse.setEnabled(true);
			}
		}
		else {
			if(jPasswordFieldContra.getText().isEmpty() || jTextFieldId.getText().isEmpty())
				jButtonRegistrarse.setEnabled(false);
			else {
				jButtonRegistrarse.setEnabled(true);
			}
		}
	}

	@Override
	public void keyTyped(KeyEvent e) {	
	}
	
	
	public void setKeyListener() {
	    this.jTextFieldDni.addKeyListener(this);
	    this.jTextFieldTelefono.addKeyListener(this);
	    this.jPasswordFieldContra.addKeyListener(this);
	    this.jTextFieldId.addKeyListener(this);
	}

	@Override
	public int getDni() {
		if(jRadioButtonFisico.isSelected())
			return Integer.parseInt(jTextFieldDni.getText());
		else {
			return Integer.parseInt(jTextFieldId.getText());
		}
	}

	@Override
	public String getContra() {
		// TODO Auto-generated method stub
		return jPasswordFieldContra.getText();
	}

	@Override
	public String getTelefono() {
		// TODO Auto-generated method stub
		return	jTextFieldTelefono.getText();
	}

	@Override
	public String getEmail() {
		// TODO Auto-generated method stub
		return jTextFieldEmail.getText();
	}

	@Override
	public String getNombre() {
		// TODO Auto-generated method stub
		return jTextFieldNombre.getText();
	}

	@Override
	public String getApellido() {
		// TODO Auto-generated method stub
		return jTextFieldApellido.getText();
	}

	@Override
	public void muestraFisico() {
		jTextFieldDni.setVisible(true);
		jTextFieldApellido.setVisible(true);
		jLabelApellido.setVisible(true);
		jLabelDni.setVisible(true);
		
		jTextFieldId.setVisible(false);
		jLabelId.setVisible(false);
		
		
	}

	@Override
	public void muestraJuridico() {
		jTextFieldId.setVisible(true);
		jLabelId.setVisible(true);
		
		
		jTextFieldDni.setVisible(false);
		jTextFieldApellido.setVisible(false);
		jLabelApellido.setVisible(false);
		jLabelDni.setVisible(false);
		
	}
	
	
	public void chequear() {
		if(jRadioButtonFisico.isSelected()) {
			if(jPasswordFieldContra.getText().isEmpty() || jTextFieldDni.getText().isEmpty())
				jButtonRegistrarse.setEnabled(false);
			else {
				jButtonRegistrarse.setEnabled(true);
			}
		}
		else {
			if(jPasswordFieldContra.getText().isEmpty() || jTextFieldId.getText().isEmpty())
				jButtonRegistrarse.setEnabled(false);
			else {
				jButtonRegistrarse.setEnabled(true);
			}
		}
	}

	@Override
	public String gettipo() {
		if(jRadioButtonFisico.isSelected())
			return "Fisico";
		else {
			return "Juridico";
		}
	}
}
